add_article_page:
  path: /add-article-page
  defaults: { _controller: '\App\Controllers\ArticlesController::addArticleAction' }

add_user_article:
  path: /add-user-article
  defaults: { _controller: '\App\Controllers\ArticlesController::addUserArticleAction' }
  methods: POST

articles_home:
  path: /
  defaults: { _controller: '\App\Controllers\ArticlesController::articlesHome' }

artilce_detail_page:
  path: /article-detail/{id}
  defaults: { _controller: '\App\Controllers\ArticlesController::articleDetail' }
  requirements:
    id: '[0-9]+'

login_page:
  path: /login
  defaults: { _controller: '\App\Controllers\AuthController::loginAction' }

user_login:
  path: /user-login
  methods:    POST
  defaults: { _controller: '\App\Controllers\AuthController::userLoginAction' }

logout_route:
  path: /logout
  defaults: { _controller: '\App\Controllers\AuthController::logoutAction' }